package simpledb.storage;

import simpledb.common.Database;
import simpledb.common.DbException;
import simpledb.common.Debug;
import simpledb.common.Permissions;
import simpledb.transaction.TransactionAbortedException;
import simpledb.transaction.TransactionId;

import java.io.*;
import java.util.*;

/**
 * HeapFile is an implementation of a DbFile that stores a collection of tuples
 * in no particular order. Tuples are stored on pages, each of which is a fixed
 * size, and the file is simply a collection of those pages. HeapFile works
 * closely with HeapPage. The format of HeapPages is described in the HeapPage
 * constructor.
 * * @see HeapPage#HeapPage
 * @author Sam Madden
 */
public class HeapFile implements DbFile {

    private final File f;
    private final TupleDesc td;

    /**
     * Constructs a heap file backed by the specified file.
     * * @param f
     * the file that stores the on-disk backing store for this heap
     * file.
     */
    public HeapFile(File f, TupleDesc td) {
        this.f = f;
        this.td = td;
    }

    /**
     * Returns the File backing this HeapFile on disk.
     * * @return the File backing this HeapFile on disk.
     */
    public File getFile() {
        return f;
    }

    /**
     * Returns an ID uniquely identifying this HeapFile. Implementation note:
     * you will need to generate this tableid somewhere to ensure that each
     * HeapFile has a "unique id," and that you always return the same value for
     * a particular HeapFile. We suggest hashing the absolute file name of the
     * file underlying the heapfile, i.e. f.getAbsoluteFile().hashCode().
     * * @return an ID uniquely identifying this HeapFile.
     */
    public int getId() {
        return f.getAbsoluteFile().hashCode();
    }

    /**
     * Returns the TupleDesc of the table stored in this DbFile.
     * * @return TupleDesc of this DbFile.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return td;
    }

    // see DbFile.java for javadocs
    public Page readPage(PageId pid) {
        // some code goes here
        int pageSize = BufferPool.getPageSize();
        byte[] data = new byte[pageSize];
        
        // RandomAccessFile allows us to jump to any byte in the file
        try (RandomAccessFile raf = new RandomAccessFile(f, "r")) {
            int offset = pid.getPageNumber() * pageSize;
            raf.seek(offset);
            raf.readFully(data);
            return new HeapPage((HeapPageId) pid, data);
        } catch (IOException e) {
            throw new IllegalArgumentException("HeapFile: Could not read page from disk");
        }
    }

    // see DbFile.java for javadocs
    public void writePage(Page page) throws IOException {
        // some code goes here
        int pageSize = BufferPool.getPageSize();
        
        // Open the file in "rw" (read-write) mode
        try (RandomAccessFile raf = new RandomAccessFile(f, "rw")) {
            // Calculate exactly where this page belongs on disk
            int offset = page.getId().getPageNumber() * pageSize;
            raf.seek(offset);
            
            // Write the raw bytes generated by HeapPage.getPageData()
            raf.write(page.getPageData());
        }
    }

    /**
     * Returns the number of pages in this HeapFile.
     */
    public int numPages() {
        // some code goes here
        return (int) (f.length() / BufferPool.getPageSize());
    }

    // see DbFile.java for javadocs
    // Updated insertTuple for Lab 3

    public List<Page> insertTuple(TransactionId tid, Tuple t)
            throws DbException, IOException, TransactionAbortedException {
        ArrayList<Page> modifiedPages = new ArrayList<>();
        
        // 1. Loop through all existing pages looking for an empty slot
        for (int i = 0; i < numPages(); i++) {
            HeapPageId pid = new HeapPageId(getId(), i);
            
            // OPTIMIZATION: Start with READ_ONLY to check for space.
            // This allows concurrent transactions to check the same page.
            HeapPage page = (HeapPage) Database.getBufferPool().getPage(tid, pid, Permissions.READ_ONLY);
            
            if (page.getNumEmptySlots() > 0) {
                // We found space! But we only have a READ lock.
                // We need to request the page again with READ_WRITE to get an Exclusive lock.
                // Our BufferPool.getPage logic handles this "upgrade" automatically.
                page = (HeapPage) Database.getBufferPool().getPage(tid, pid, Permissions.READ_WRITE);
                
                // Re-check just in case someone else filled it between our two getPage calls
                if (page.getNumEmptySlots() > 0) {
                    page.insertTuple(t);
                    modifiedPages.add(page);
                    return modifiedPages;
                }
            } else {
                // EXERCISE 2 OPTIMIZATION:
                // If the page is full, we didn't use any data. 
                // Release the lock immediately to improve concurrency.
                Database.getBufferPool().unsafeReleasePage(tid, pid);
            }
        }
        
        // 2. If we reach here, we must append a new page.
        // We synchronize on 'this' (the HeapFile) to prevent two threads 
        // from appending the same page number simultaneously.
        synchronized (this) {
            int newPageNo = numPages();
            HeapPageId newPid = new HeapPageId(getId(), newPageNo);
            HeapPage blankPage = new HeapPage(newPid, HeapPage.createEmptyPageData());
            
            // Physically grow the file
            writePage(blankPage);
            
            // Fetch the new page via BufferPool to get the X-Lock
            HeapPage newPage = (HeapPage) Database.getBufferPool().getPage(tid, newPid, Permissions.READ_WRITE);
            newPage.insertTuple(t);
            modifiedPages.add(newPage);
            return modifiedPages;
        }
    }

    // see DbFile.java for javadocs
    public ArrayList<Page> deleteTuple(TransactionId tid, Tuple t) throws DbException,
            TransactionAbortedException {
        // some code goes here
        RecordId rid = t.getRecordId();
        
        // Validate that this tuple actually belongs to this specific table/file
        if (rid == null || rid.getPageId().getTableId() != getId()) {
            throw new DbException("Tuple does not belong to this HeapFile.");
        }
        
        // Extract the exact page ID where this tuple lives
        HeapPageId pid = (HeapPageId) rid.getPageId();
        
        // Fetch the page from the BufferPool
        HeapPage page = (HeapPage) Database.getBufferPool().getPage(tid, pid, Permissions.READ_WRITE);
        
        // Tell the page to delete the tuple
        page.deleteTuple(t);
        
        ArrayList<Page> modifiedPages = new ArrayList<>();
        modifiedPages.add(page);
        
        return modifiedPages;
    }

    // see DbFile.java for javadocs
    public DbFileIterator iterator(TransactionId tid) {
        // some code goes here
        return new HeapFileIterator(this, tid);
    }
}

/**
 * Helper class that implements DbFileIterator.
 */
class HeapFileIterator implements DbFileIterator {
    private final HeapFile hf;
    private final TransactionId tid;
    private int curPageNum;
    private Iterator<Tuple> curPageIterator;

    public HeapFileIterator(HeapFile hf, TransactionId tid) {
        this.hf = hf;
        this.tid = tid;
        this.curPageIterator = null; // Ensure it starts null
    }

    @Override
    public void open() throws DbException, TransactionAbortedException {
        curPageNum = 0;
        // Only attempt to load if there is at least one page
        if (hf.numPages() > 0) {
            curPageIterator = getPageIterator(curPageNum);
        } else {
            // Empty file: iterator stays empty
            curPageIterator = Collections.emptyIterator();
        }
    }

    private Iterator<Tuple> getPageIterator(int pageNo) 
            throws DbException, TransactionAbortedException {
        HeapPageId pid = new HeapPageId(hf.getId(), pageNo);
        // This MUST return a non-null page if BufferPool is working
        HeapPage page = (HeapPage) Database.getBufferPool().getPage(tid, pid, Permissions.READ_ONLY);
        return page.iterator();
    }

    @Override
    public boolean hasNext() throws DbException, TransactionAbortedException {
        if (curPageIterator == null) return false;

        // While current iterator is empty, try the next page
        while (!curPageIterator.hasNext() && curPageNum < hf.numPages() - 1) {
            curPageNum++;
            curPageIterator = getPageIterator(curPageNum);
        }
        
        return curPageIterator.hasNext();
    }

    @Override
    public Tuple next() throws DbException, TransactionAbortedException, NoSuchElementException {
        if (!hasNext()) throw new NoSuchElementException("No more tuples");
        return curPageIterator.next();
    }

    @Override
    public void rewind() throws DbException, TransactionAbortedException {
        open();
    }

    @Override
    public void close() {
        curPageIterator = null;
    }
}